Add admin action for removing site replication
minio/pkg pull request #24
Opened 2022-01-14 01:53 UTC by poornas

2022-01-14 02:50 UTC, harshavardhana requested changes

2022-01-14 02:50 UTC, harshavardhana commented on iam/policy/admin-action.go
> +	SiteReplicationRemoveAction = "admin:SiteReplicationRemove"
We can't remove actions in this manner @poornas you should leave the Disable as is only add new actions as needed. 

Also supportedAdminActions is missing most of the Site* calls they need to be added.

2022-01-25 05:18 UTC, harshavardhana approved these changes

2022-01-25 05:19 UTC, harshavardhana commented
PTAL @donatello

2022-01-25 06:30 UTC, donatello approved these changes

2022-01-25 06:38 UTC, merged