Add IAM policies  to control access to minio handlers that will communicate with KES
minio/pkg pull request #38
Opened 2022-08-31 20:12 UTC by reivaj05

Adds IAM policies  to control access to minio handlers that will communicate with KES.

The handlers will be added in minio in another PR in which i'm currently working on.

Please let me know if there are more places where i need to make changes since this is the first time i work with policies.

Closes: https://github.com/miniohq/engineering/issues/924

2022-08-31 23:28 UTC, cniackz approved these changes
I don't know of any other places, but this change looks good to me.
Let's wait for Daniel, Lenin and Senior guys to see if they know more of it to help here.

2022-09-06 17:26 UTC, Alevsk approved these changes

2022-09-06 17:26 UTC, Alevsk commented
Does this looks good @harshavardhana  ?

2022-09-07 23:44 UTC, harshavardhana commented
are we going to implement these handlers at MinIO or Kes @Alevsk @reivaj05 ?

2022-09-07 23:49 UTC, harshavardhana requested changes
Let's discuss this first - if we are going to do this then I would suggest we add `kms:CreateKey` like actions instead of `admin:*` 

This allows us to have special Conditions and have all the S3 API-related functionality.

2022-09-13 21:25 UTC, closed without merging

2022-09-13 21:25 UTC, reivaj05 commented
no need