net.Listener does not close when context.cancelFunc is called.
minio/pkg pull request #87
Opened 2023-11-22 13:31 UTC by zveinn

Apparently the net.Listener does not respect the cancelFunc call. Instead we have to directly call .Close()

2023-11-22 16:13 UTC, harshavardhana requested changes

2023-11-22 16:13 UTC, harshavardhana commented on go.mod
> +go 1.21.1
```suggestion
go 1.20
```

2023-11-22 16:13 UTC, harshavardhana commented on .github/workflows/vulncheck.yml
> +        go-version: [ 1.21.x ]
```suggestion
        go-version: [ 1.20.x, 1.21.x ]
```

2023-11-22 16:13 UTC, harshavardhana commented on .github/workflows/ldap.yaml
> +        go-version: [1.21.x]
```suggestion
        go-version: [ 1.20.x, 1.21.x ]
```

2023-11-22 18:06 UTC, vadmeste approved these changes
LGTM

2023-11-27 09:27 UTC, harshavardhana approved these changes

2023-11-27 09:29 UTC, merged