add GetThemeColor
minio/pkg pull request #97
Opened 2024-02-22 03:33 UTC by jiuker

add GetThemeColor

2024-02-22 04:02 UTC, shtripat commented
Can you please explain the usecase in description a bit?

2024-02-22 11:33 UTC, vadmeste requested changes

2024-02-22 11:33 UTC, vadmeste commented on console/themes.go
> +func GetThemeColor(tag string) (*color.Color, bool) {
Can you use getThemeColor to avoid code duplication ?

2024-02-22 14:02 UTC, vadmeste approved these changes
LGTM

2024-02-22 15:42 UTC, shtripat approved these changes

2024-02-23 02:10 UTC, kannappanr approved these changes

2024-02-23 07:11 UTC, closed without merging

2024-02-23 08:45 UTC, jiuker commented
No need any more.